version: "3.3"
services:
  backend-webserver:
    build: backend/
    networks:
      - dev-net
    depends_on:
      - database
    restart: "no"
    ports:
      - "3000:3000"
    command: sh -c "./wait-for-it.sh -t 20 database:5432 -- node ./build/server.js"
  database:
    image: postgres:12
    restart: always
    networks:
      dev-net:
        aliases:
          - app-database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
      POSTGRES_DB: app_db
    volumes:
      - ../ese-db-volume:/var/lib/postgresql/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - dev-net
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=app-database
  frontend-webserver:
    build: frontend/
    networks:
      - dev-net
    ports:
      - "8100:4200"
    restart: "no"
    command: npm run ng serve
networks:
  dev-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
